"""
Django settings for koki_foodhub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file only in development or when explicitly enabled.
# This avoids accidentally loading a checked-in .env in production (e.g., on Render).
if os.getenv("USE_DOTENV", "").lower() == "true" or os.getenv("ENV", "").lower() in ("development", "dev"):
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", 'django-insecure-change-me-in-production-now')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local development, False in production (when explicitly set).
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# Character encoding settings
FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'

# Security settings for production (Render has HTTPS)
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver,.onrender.com").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # If the DB is unavailable, return a friendly 503 page instead of
    # exposing raw db errors in templates. Keep this early in the chain so
    # it catches OperationalError raised by views.
    'core.middleware.db_unavailable.DBUnavailableMiddleware',
    # Ensure DB connections are fresh at each request to avoid stale
    # 'connection already closed' errors in long-running workers.
    'core.middleware.db.DBConnectionMiddleware',
    # Global handler to ensure uncontrolled exceptions in forecast endpoints are logged
    # with an Error ID and returned to clients in a safe (JSON or HTML) format.
    'core.middleware.forecast_exceptions.ForecastExceptionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'koki_foodhub.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",  # <-- add this line
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'koki_foodhub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE: SQLite default; set POSTGRES_* envs to switch
# Prefer explicit DATABASE_URL (Render provides this when using a managed Postgres)

def _find_render_database_url():
    # Common explicit name
    candidates = [
        'DATABASE_URL',
        'KOKI_FOODHUB_DB_DATABASE_URL',
        'koki-foodhub-db_DATABASE_URL',
        'kokifoodhub_db_DATABASE_URL',
        'KOKIFOODHUB_DB_DATABASE_URL',
    ]
    for name in candidates:
        val = os.getenv(name)
        if val:
            return val

    # Search environment for any DATABASE_URL variable related to this project
    for name, val in os.environ.items():
        if name.endswith('_DATABASE_URL') and val:
            lname = name.lower()
            if 'foodhub' in lname or 'koki' in lname or 'kokifoodhub' in lname:
                return val

    # If there's only a single *_DATABASE_URL set, prefer that
    db_urls = [v for k, v in os.environ.items() if k.endswith('_DATABASE_URL') and v]
    if len(db_urls) == 1:
        return db_urls[0]

    return os.getenv('DATABASE_URL')

DATABASE_URL = _find_render_database_url()

# If the chosen DATABASE_URL points to localhost, but another *_DATABASE_URL
# exists that points to a remote host, prefer the remote one. This prevents
# accidentally using a local connection string present in the environment.
def _choose_non_local_db(url_candidate: str):
    try:
        from urllib.parse import urlparse
        if not url_candidate:
            return None
        p = urlparse(url_candidate)
        host = (p.hostname or '').lower()
        if host and host not in ('localhost', '127.0.0.1'):
            return url_candidate
    except Exception:
        pass
    # scan for alternatives
    for name, val in os.environ.items():
        if name.endswith('_DATABASE_URL') and val:
            try:
                from urllib.parse import urlparse
                p = urlparse(val)
                host = (p.hostname or '').lower()
                if host and host not in ('localhost', '127.0.0.1'):
                    return val
            except Exception:
                continue
    return url_candidate

DATABASE_URL = _choose_non_local_db(DATABASE_URL)

# Fail fast in production when DATABASE_URL is missing or points to localhost.
# This prevents the app from attempting to connect to a local Postgres that
# does not exist on hosted platforms (e.g., Render) and surfaces the
# configuration problem with a clear message.
if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    if not DATABASE_URL:
        raise ImproperlyConfigured(
            "DATABASE_URL environment variable is required in production. "
            "Set it to your Render Postgres URL (see RENDER_DEPLOYMENT_STEPS.md)."
        )
    try:
        from urllib.parse import urlparse
        p = urlparse(DATABASE_URL)
        host = (p.hostname or "").lower()
        if host in ("localhost", "127.0.0.1", ""):
            raise ImproperlyConfigured(
                f"DATABASE_URL points to localhost ({host}) in production. "
                "Use the managed Render Postgres DATABASE_URL or set a remote host."
            )
    except ImproperlyConfigured:
        raise
    except Exception:
        raise ImproperlyConfigured(
            "DATABASE_URL is malformed. Ensure it follows: postgresql://user:pass@host:port/dbname"
        )

# In development (DEBUG=True) prefer the local SQLite fallback even if
# a DATABASE_URL or POSTGRES_* env vars exist. This prevents the app from
# attempting to connect to a non-running local Postgres instance during
# developer runs. In production (DEBUG=False) DATABASE_URL / POSTGRES_* are
# honored as before.
if DATABASE_URL and not DEBUG:
    # Parse DATABASE_URL manually for PostgreSQL connection
    from urllib.parse import urlparse
    url = urlparse(DATABASE_URL)
    db_name = url.path[1:] if url.path else 'koki_foodhub'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': url.username or 'postgres',
            'PASSWORD': url.password or '',
            'HOST': url.hostname or 'localhost',
            'PORT': url.port or 5432,
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'connect_timeout': 10,
                # Render requires SSL connections; allow override with PGSSLMODE env var
                'sslmode': os.getenv('PGSSLMODE', 'require'),
            }
        }
    }
elif os.getenv("POSTGRES_HOST") and not DEBUG:
    # Fallback to individual POSTGRES_* environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("POSTGRES_NAME", "koki_foodhub"),
            'USER': os.getenv("POSTGRES_USER", "postgres"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD", ""),
            'HOST': os.getenv("POSTGRES_HOST", "localhost"),
            'PORT': os.getenv("POSTGRES_PORT", "5432"),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'sslmode': os.getenv('PGSSLMODE', 'require'),
            },
        }
    }
else:
    # SQLite fallback for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3"
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Always include static directory if it exists
STATICFILES_DIRS = []
_static_dir = BASE_DIR / 'static'
if _static_dir.exists():
    STATICFILES_DIRS.append(_static_dir)

# Also include core app static files
_core_static = BASE_DIR / 'core' / 'static'
if _core_static.exists():
    STATICFILES_DIRS.append(_core_static)

# WhiteNoise configuration for production static file serving
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configure WhiteNoise to serve files with caching
WHITENOISE_COMPRESS = True
WHITENOISE_COMPRESSION_QUALITY = 80
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Configure WhiteNoise to also serve media files
WHITENOISE_MIMETYPES = {
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
}

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# CSRF and Session Configuration
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://koki-foodhub-app.onrender.com',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if not DEBUG else 'None'

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax' if not DEBUG else 'None'

# AWS S3 Configuration for persistent media storage on Render
# This is optional - only configure if S3 credentials are provided
if os.getenv('AWS_ACCESS_KEY_ID') and os.getenv('AWS_SECRET_ACCESS_KEY'):
    # Use S3 for media storage
    INSTALLED_APPS.insert(0, 'storages')  # Add django-storages
    
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'koki-foodhub-media')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_LOCATION = 'media'
    
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # Cache settings
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH = False
